font:
  size: "8px"
  weight: "bold"
  style: "italic"

title: JL Christian
title: "8px"
logo: assets/fonts/img/jlc-avatar.png
description: Fine Artist | Art Curator

google_analytics:
theme: jekyll-theme-minimal
