title: 

logo: assets/fonts/img/jlc-avatar.png
description: JL Christian 
Fine Artist | Art Curator

google_analytics:
theme: jekyll-theme-minimal
environment:
  TEXT_SIZE: "12pt"
  FONT_FAMILY: "Arial"
