title: 
  text: "JL Christian"
  size: "24px"    # Specifies the font size of the title
  color: "#333333"  # Optional: Sets the color of the title
  font_weight: "bold"  # Optional: Sets the font weight

logo: assets/fonts/img/jlc-avatar.png
description: Fine Artist | Art Curator

google_analytics:
theme: jekyll-theme-minimal
