title: J.L. Christian 
logo: docs/assets/jlc-avatar.png
description: 
Jonathan L. Christian (J.L. Christian) stands as a powerful voice in the world of fine art, bringing a unique blend of storytelling and visual mastery to every piece he creates. Born in San Francisco and raised in Oakland, California, Jonathan’s artistic journey began with illustration and a career in graphic design, where he honed the technical skills that would later inform his distinct artistic approach. But beyond the structured world of design, his true passion lay in fine art—a passion sparked by his father, George E. Christian, whose deep appreciation for art became a lifelong source of inspiration.
#show_downloadeds: true
theme: jekyll-theme-minimal
